WORK_DIR: "H:/Projects/UNet3P/"

DATA_PREPARATION:
  RESIZED_HEIGHT: 320
  RESIZED_WIDTH: 320

  SCAN_MIN_VALUE: -200
  SCAN_MAX_VALUE: 250

  # unprocessed scan data paths
  SCANS_TRAIN_DATA_PATH: "/data/Training Batch 2/"
  SCANS_VAL_DATA_PATH: "/data/Training Batch 1/"

PATHS:
  TRAIN:
    IMAGES_PATH: "/data/train/"
    MASK_PATH: "/data/train/"
    CHECKPOINT_PATH: ""
    TB_LOG_PATH: ""
  VAL:
    IMAGES_PATH: "/data/val/"
    MASK_PATH: "/data/val/"

INPUT:
  HEIGHT: 320
  WIDTH: 320
  CHANNELS: 3

OUTPUT:
  CLASSES: 2


#TRAINING_HYPER_PARAMETERS:
HYPER_PARAMETERS:
  BATCH_SIZE: 5
  EPOCHS: 5
  LEARNING_RATE: 3e-4  # 1e-3 # 0.001 # 3e-4


PREPROCESS_DATA:
  RESIZE:
    VALUE: False
    HEIGHT: None
    WIDTH: None

  COLOR_CODE: RGB
  PREPROCESSING_TYPE: "normalize"

  NORMALIZE_MASK:
    VALUE: FALSE
    NORMALIZE_VALUE: 255



#TRAINING:
#  TRAIN:
#    data_path: "/data/train/"
#    shuffle: True
#  VAL:
#    data_path: "/data/val/"
#    shuffle: False
#
#  HYPER_PARAMETERS:
#    sss: sd



# to stop hydra from storing logs files
defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
